=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  class GistsCreateRequestPublicOneOf
    TRUE = "true".freeze
    FALSE = "false".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = GistsCreateRequestPublicOneOf.constants.select { |c| GistsCreateRequestPublicOneOf::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #GistsCreateRequestPublicOneOf" if constantValues.empty?
      value
    end
  end
end
