=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'date'
require 'time'

module OpenapiClient
  # Timeline Event
  class TimelineEvent
    attr_accessor :id

    attr_accessor :node_id

    attr_accessor :url

    attr_accessor :actor

    attr_accessor :event

    attr_accessor :commit_id

    attr_accessor :commit_url

    attr_accessor :created_at

    attr_accessor :performed_via_github_app

    attr_accessor :label

    attr_accessor :milestone

    attr_accessor :rename

    attr_accessor :review_requester

    attr_accessor :requested_team

    attr_accessor :requested_reviewer

    attr_accessor :dismissed_review

    attr_accessor :lock_reason

    attr_accessor :project_card

    # The text of the review.
    attr_accessor :body

    attr_accessor :body_text

    attr_accessor :body_html

    attr_accessor :html_url

    attr_accessor :user

    attr_accessor :updated_at

    attr_accessor :issue_url

    # How the author is associated with the repository.
    attr_accessor :author_association

    attr_accessor :reactions

    attr_accessor :source

    # SHA for the commit
    attr_accessor :sha

    attr_accessor :author

    attr_accessor :committer

    # Message describing the purpose of the commit
    attr_accessor :message

    attr_accessor :tree

    attr_accessor :parents

    attr_accessor :verification

    attr_accessor :state

    attr_accessor :pull_request_url

    attr_accessor :_links

    attr_accessor :submitted_at

    attr_accessor :comments

    attr_accessor :assignee

    attr_accessor :state_reason

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'node_id' => :'node_id',
        :'url' => :'url',
        :'actor' => :'actor',
        :'event' => :'event',
        :'commit_id' => :'commit_id',
        :'commit_url' => :'commit_url',
        :'created_at' => :'created_at',
        :'performed_via_github_app' => :'performed_via_github_app',
        :'label' => :'label',
        :'milestone' => :'milestone',
        :'rename' => :'rename',
        :'review_requester' => :'review_requester',
        :'requested_team' => :'requested_team',
        :'requested_reviewer' => :'requested_reviewer',
        :'dismissed_review' => :'dismissed_review',
        :'lock_reason' => :'lock_reason',
        :'project_card' => :'project_card',
        :'body' => :'body',
        :'body_text' => :'body_text',
        :'body_html' => :'body_html',
        :'html_url' => :'html_url',
        :'user' => :'user',
        :'updated_at' => :'updated_at',
        :'issue_url' => :'issue_url',
        :'author_association' => :'author_association',
        :'reactions' => :'reactions',
        :'source' => :'source',
        :'sha' => :'sha',
        :'author' => :'author',
        :'committer' => :'committer',
        :'message' => :'message',
        :'tree' => :'tree',
        :'parents' => :'parents',
        :'verification' => :'verification',
        :'state' => :'state',
        :'pull_request_url' => :'pull_request_url',
        :'_links' => :'_links',
        :'submitted_at' => :'submitted_at',
        :'comments' => :'comments',
        :'assignee' => :'assignee',
        :'state_reason' => :'state_reason'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'node_id' => :'String',
        :'url' => :'String',
        :'actor' => :'SimpleUser1',
        :'event' => :'String',
        :'commit_id' => :'String',
        :'commit_url' => :'String',
        :'created_at' => :'String',
        :'performed_via_github_app' => :'GitHubApp1',
        :'label' => :'LabeledIssueEventLabel',
        :'milestone' => :'MilestonedIssueEventMilestone',
        :'rename' => :'RenamedIssueEventRename',
        :'review_requester' => :'SimpleUser1',
        :'requested_team' => :'Team',
        :'requested_reviewer' => :'SimpleUser1',
        :'dismissed_review' => :'ReviewDismissedIssueEventDismissedReview',
        :'lock_reason' => :'String',
        :'project_card' => :'AddedToProjectIssueEventProjectCard',
        :'body' => :'String',
        :'body_text' => :'String',
        :'body_html' => :'String',
        :'html_url' => :'String',
        :'user' => :'SimpleUser1',
        :'updated_at' => :'Time',
        :'issue_url' => :'String',
        :'author_association' => :'String',
        :'reactions' => :'ReactionRollup',
        :'source' => :'TimelineCrossReferencedEventSource',
        :'sha' => :'String',
        :'author' => :'GitCommitAuthor',
        :'committer' => :'GitCommitAuthor',
        :'message' => :'String',
        :'tree' => :'GitCommitTree',
        :'parents' => :'Array<GitCommitParentsInner>',
        :'verification' => :'GitCommitVerification',
        :'state' => :'String',
        :'pull_request_url' => :'String',
        :'_links' => :'TimelineReviewedEventLinks',
        :'submitted_at' => :'Time',
        :'comments' => :'Array<CommitComment>',
        :'assignee' => :'SimpleUser1',
        :'state_reason' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'commit_id',
        :'commit_url',
        :'performed_via_github_app',
        :'lock_reason',
        :'body',
        :'state_reason'
      ])
    end

    # List of class defined in anyOf (OpenAPI v3)
    def self.openapi_any_of
      [
      :'AddedToProjectIssueEvent',
      :'ConvertedNoteToIssueIssueEvent',
      :'DemilestonedIssueEvent',
      :'LabeledIssueEvent',
      :'LockedIssueEvent',
      :'MilestonedIssueEvent',
      :'MovedColumnInProjectIssueEvent',
      :'RemovedFromProjectIssueEvent',
      :'RenamedIssueEvent',
      :'ReviewDismissedIssueEvent',
      :'ReviewRequestRemovedIssueEvent',
      :'ReviewRequestedIssueEvent',
      :'StateChangeIssueEvent',
      :'TimelineAssignedIssueEvent',
      :'TimelineCommentEvent',
      :'TimelineCommitCommentedEvent',
      :'TimelineCommittedEvent',
      :'TimelineCrossReferencedEvent',
      :'TimelineLineCommentedEvent',
      :'TimelineReviewedEvent',
      :'TimelineUnassignedIssueEvent',
      :'UnlabeledIssueEvent'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::TimelineEvent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::TimelineEvent`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'node_id')
        self.node_id = attributes[:'node_id']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'actor')
        self.actor = attributes[:'actor']
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      end

      if attributes.key?(:'commit_id')
        self.commit_id = attributes[:'commit_id']
      end

      if attributes.key?(:'commit_url')
        self.commit_url = attributes[:'commit_url']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'performed_via_github_app')
        self.performed_via_github_app = attributes[:'performed_via_github_app']
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      end

      if attributes.key?(:'milestone')
        self.milestone = attributes[:'milestone']
      end

      if attributes.key?(:'rename')
        self.rename = attributes[:'rename']
      end

      if attributes.key?(:'review_requester')
        self.review_requester = attributes[:'review_requester']
      end

      if attributes.key?(:'requested_team')
        self.requested_team = attributes[:'requested_team']
      end

      if attributes.key?(:'requested_reviewer')
        self.requested_reviewer = attributes[:'requested_reviewer']
      end

      if attributes.key?(:'dismissed_review')
        self.dismissed_review = attributes[:'dismissed_review']
      end

      if attributes.key?(:'lock_reason')
        self.lock_reason = attributes[:'lock_reason']
      end

      if attributes.key?(:'project_card')
        self.project_card = attributes[:'project_card']
      end

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      end

      if attributes.key?(:'body_text')
        self.body_text = attributes[:'body_text']
      end

      if attributes.key?(:'body_html')
        self.body_html = attributes[:'body_html']
      end

      if attributes.key?(:'html_url')
        self.html_url = attributes[:'html_url']
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'issue_url')
        self.issue_url = attributes[:'issue_url']
      end

      if attributes.key?(:'author_association')
        self.author_association = attributes[:'author_association']
      end

      if attributes.key?(:'reactions')
        self.reactions = attributes[:'reactions']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'sha')
        self.sha = attributes[:'sha']
      end

      if attributes.key?(:'author')
        self.author = attributes[:'author']
      end

      if attributes.key?(:'committer')
        self.committer = attributes[:'committer']
      end

      if attributes.key?(:'message')
        self.message = attributes[:'message']
      end

      if attributes.key?(:'tree')
        self.tree = attributes[:'tree']
      end

      if attributes.key?(:'parents')
        if (value = attributes[:'parents']).is_a?(Array)
          self.parents = value
        end
      end

      if attributes.key?(:'verification')
        self.verification = attributes[:'verification']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'pull_request_url')
        self.pull_request_url = attributes[:'pull_request_url']
      end

      if attributes.key?(:'_links')
        self._links = attributes[:'_links']
      end

      if attributes.key?(:'submitted_at')
        self.submitted_at = attributes[:'submitted_at']
      end

      if attributes.key?(:'comments')
        if (value = attributes[:'comments']).is_a?(Array)
          self.comments = value
        end
      end

      if attributes.key?(:'assignee')
        self.assignee = attributes[:'assignee']
      end

      if attributes.key?(:'state_reason')
        self.state_reason = attributes[:'state_reason']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @node_id.nil?
        invalid_properties.push('invalid value for "node_id", node_id cannot be nil.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @actor.nil?
        invalid_properties.push('invalid value for "actor", actor cannot be nil.')
      end

      if @event.nil?
        invalid_properties.push('invalid value for "event", event cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @milestone.nil?
        invalid_properties.push('invalid value for "milestone", milestone cannot be nil.')
      end

      if @rename.nil?
        invalid_properties.push('invalid value for "rename", rename cannot be nil.')
      end

      if @review_requester.nil?
        invalid_properties.push('invalid value for "review_requester", review_requester cannot be nil.')
      end

      if @dismissed_review.nil?
        invalid_properties.push('invalid value for "dismissed_review", dismissed_review cannot be nil.')
      end

      if @html_url.nil?
        invalid_properties.push('invalid value for "html_url", html_url cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @issue_url.nil?
        invalid_properties.push('invalid value for "issue_url", issue_url cannot be nil.')
      end

      if @author_association.nil?
        invalid_properties.push('invalid value for "author_association", author_association cannot be nil.')
      end

      if @source.nil?
        invalid_properties.push('invalid value for "source", source cannot be nil.')
      end

      if @sha.nil?
        invalid_properties.push('invalid value for "sha", sha cannot be nil.')
      end

      if @author.nil?
        invalid_properties.push('invalid value for "author", author cannot be nil.')
      end

      if @committer.nil?
        invalid_properties.push('invalid value for "committer", committer cannot be nil.')
      end

      if @message.nil?
        invalid_properties.push('invalid value for "message", message cannot be nil.')
      end

      if @tree.nil?
        invalid_properties.push('invalid value for "tree", tree cannot be nil.')
      end

      if @parents.nil?
        invalid_properties.push('invalid value for "parents", parents cannot be nil.')
      end

      if @verification.nil?
        invalid_properties.push('invalid value for "verification", verification cannot be nil.')
      end

      if @state.nil?
        invalid_properties.push('invalid value for "state", state cannot be nil.')
      end

      if @pull_request_url.nil?
        invalid_properties.push('invalid value for "pull_request_url", pull_request_url cannot be nil.')
      end

      if @_links.nil?
        invalid_properties.push('invalid value for "_links", _links cannot be nil.')
      end

      if @assignee.nil?
        invalid_properties.push('invalid value for "assignee", assignee cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @node_id.nil?
      return false if @url.nil?
      return false if @actor.nil?
      return false if @event.nil?
      return false if @created_at.nil?
      return false if @label.nil?
      return false if @milestone.nil?
      return false if @rename.nil?
      return false if @review_requester.nil?
      return false if @dismissed_review.nil?
      return false if @html_url.nil?
      return false if @user.nil?
      return false if @updated_at.nil?
      return false if @issue_url.nil?
      return false if @author_association.nil?
      author_association_validator = EnumAttributeValidator.new('String', ["COLLABORATOR", "CONTRIBUTOR", "FIRST_TIMER", "FIRST_TIME_CONTRIBUTOR", "MANNEQUIN", "MEMBER", "NONE", "OWNER"])
      return false unless author_association_validator.valid?(@author_association)
      return false if @source.nil?
      return false if @sha.nil?
      return false if @author.nil?
      return false if @committer.nil?
      return false if @message.nil?
      return false if @tree.nil?
      return false if @parents.nil?
      return false if @verification.nil?
      return false if @state.nil?
      return false if @pull_request_url.nil?
      return false if @_links.nil?
      return false if @assignee.nil?
      _any_of_found = false
      self.class.openapi_any_of.each do |_class|
        _any_of = OpenapiClient.const_get(_class).build_from_hash(self.to_hash)
        if _any_of.valid?
          _any_of_found = true
        end
      end

      if !_any_of_found
        return false
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] author_association Object to be assigned
    def author_association=(author_association)
      validator = EnumAttributeValidator.new('String', ["COLLABORATOR", "CONTRIBUTOR", "FIRST_TIMER", "FIRST_TIME_CONTRIBUTOR", "MANNEQUIN", "MEMBER", "NONE", "OWNER"])
      unless validator.valid?(author_association)
        fail ArgumentError, "invalid value for \"author_association\", must be one of #{validator.allowable_values}."
      end
      @author_association = author_association
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          node_id == o.node_id &&
          url == o.url &&
          actor == o.actor &&
          event == o.event &&
          commit_id == o.commit_id &&
          commit_url == o.commit_url &&
          created_at == o.created_at &&
          performed_via_github_app == o.performed_via_github_app &&
          label == o.label &&
          milestone == o.milestone &&
          rename == o.rename &&
          review_requester == o.review_requester &&
          requested_team == o.requested_team &&
          requested_reviewer == o.requested_reviewer &&
          dismissed_review == o.dismissed_review &&
          lock_reason == o.lock_reason &&
          project_card == o.project_card &&
          body == o.body &&
          body_text == o.body_text &&
          body_html == o.body_html &&
          html_url == o.html_url &&
          user == o.user &&
          updated_at == o.updated_at &&
          issue_url == o.issue_url &&
          author_association == o.author_association &&
          reactions == o.reactions &&
          source == o.source &&
          sha == o.sha &&
          author == o.author &&
          committer == o.committer &&
          message == o.message &&
          tree == o.tree &&
          parents == o.parents &&
          verification == o.verification &&
          state == o.state &&
          pull_request_url == o.pull_request_url &&
          _links == o._links &&
          submitted_at == o.submitted_at &&
          comments == o.comments &&
          assignee == o.assignee &&
          state_reason == o.state_reason
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, node_id, url, actor, event, commit_id, commit_url, created_at, performed_via_github_app, label, milestone, rename, review_requester, requested_team, requested_reviewer, dismissed_review, lock_reason, project_card, body, body_text, body_html, html_url, user, updated_at, issue_url, author_association, reactions, source, sha, author, committer, message, tree, parents, verification, state, pull_request_url, _links, submitted_at, comments, assignee, state_reason].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
