=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ActionsGetWorkflowAccessToRepository200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ActionsGetWorkflowAccessToRepository200Response do
  let(:instance) { OpenapiClient::ActionsGetWorkflowAccessToRepository200Response.new }

  describe 'test an instance of ActionsGetWorkflowAccessToRepository200Response' do
    it 'should create an instance of ActionsGetWorkflowAccessToRepository200Response' do
      expect(instance).to be_instance_of(OpenapiClient::ActionsGetWorkflowAccessToRepository200Response)
    end
  end
  describe 'test attribute "access_level"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "user", "organization", "enterprise"])
      # validator.allowable_values.each do |value|
      #   expect { instance.access_level = value }.not_to raise_error
      # end
    end
  end

end
