=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequest do
  let(:instance) { OpenapiClient::EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequest.new }

  describe 'test an instance of EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequest' do
    it 'should create an instance of EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequest' do
      expect(instance).to be_instance_of(OpenapiClient::EnterpriseAdminSetOrgAccessToSelfHostedRunnerGroupInEnterpriseRequest)
    end
  end
  describe 'test attribute "selected_organization_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
