=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GistsCreateRequestPublicOneOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GistsCreateRequestPublicOneOf do
  let(:instance) { OpenapiClient::GistsCreateRequestPublicOneOf.new }

  describe 'test an instance of GistsCreateRequestPublicOneOf' do
    it 'should create an instance of GistsCreateRequestPublicOneOf' do
      expect(instance).to be_instance_of(OpenapiClient::GistsCreateRequestPublicOneOf)
    end
  end
end
