/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActionsUpdateSelfHostedRunnerGroupForOrgRequest {
    /**
    * Name of the runner group.
    */
    'name': string;
    /**
    * Visibility of a runner group. You can select all repositories, select individual repositories, or all private repositories.
    */
    'visibility'?: ActionsUpdateSelfHostedRunnerGroupForOrgRequest.VisibilityEnum;
    /**
    * Whether the runner group can be used by `public` repositories.
    */
    'allowsPublicRepositories'?: boolean = false;
    /**
    * If `true`, the runner group will be restricted to running only the workflows specified in the `selected_workflows` array.
    */
    'restrictedToWorkflows'?: boolean = false;
    /**
    * List of workflows the runner group should be allowed to run. This setting will be ignored unless `restricted_to_workflows` is set to `true`.
    */
    'selectedWorkflows'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "ActionsUpdateSelfHostedRunnerGroupForOrgRequest.VisibilityEnum"
        },
        {
            "name": "allowsPublicRepositories",
            "baseName": "allows_public_repositories",
            "type": "boolean"
        },
        {
            "name": "restrictedToWorkflows",
            "baseName": "restricted_to_workflows",
            "type": "boolean"
        },
        {
            "name": "selectedWorkflows",
            "baseName": "selected_workflows",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ActionsUpdateSelfHostedRunnerGroupForOrgRequest.attributeTypeMap;
    }
}

export namespace ActionsUpdateSelfHostedRunnerGroupForOrgRequest {
    export enum VisibilityEnum {
        Selected = <any> 'selected',
        All = <any> 'all',
        Private = <any> 'private'
    }
}
