/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AppsCreateFromManifest201ResponseAllOf extends null<String, any> {
    'clientId': string;
    'clientSecret': string;
    'webhookSecret': string | null;
    'pem': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string"
        },
        {
            "name": "clientSecret",
            "baseName": "client_secret",
            "type": "string"
        },
        {
            "name": "webhookSecret",
            "baseName": "webhook_secret",
            "type": "string"
        },
        {
            "name": "pem",
            "baseName": "pem",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(AppsCreateFromManifest201ResponseAllOf.attributeTypeMap);
    }
}

