/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BranchRestrictionPolicyTeamsInner {
    'id'?: number;
    'nodeId'?: string;
    'url'?: string;
    'htmlUrl'?: string;
    'name'?: string;
    'slug'?: string;
    'description'?: string | null;
    'privacy'?: string;
    'permission'?: string;
    'membersUrl'?: string;
    'repositoriesUrl'?: string;
    'parent'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "htmlUrl",
            "baseName": "html_url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "privacy",
            "baseName": "privacy",
            "type": "string"
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "string"
        },
        {
            "name": "membersUrl",
            "baseName": "members_url",
            "type": "string"
        },
        {
            "name": "repositoriesUrl",
            "baseName": "repositories_url",
            "type": "string"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BranchRestrictionPolicyTeamsInner.attributeTypeMap;
    }
}

