/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ChecksSetSuitesPreferencesRequestAutoTriggerChecksInner {
    /**
    * The `id` of the GitHub App.
    */
    'appId': number;
    /**
    * Set to `true` to enable automatic creation of CheckSuite events upon pushes to the repository, or `false` to disable them.
    */
    'setting': boolean = true;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appId",
            "baseName": "app_id",
            "type": "number"
        },
        {
            "name": "setting",
            "baseName": "setting",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ChecksSetSuitesPreferencesRequestAutoTriggerChecksInner.attributeTypeMap;
    }
}

