/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Check Annotation
*/
export class CheckAnnotation {
    'path': string;
    'startLine': number;
    'endLine': number;
    'startColumn': number | null;
    'endColumn': number | null;
    'annotationLevel': string | null;
    'title': string | null;
    'message': string | null;
    'rawDetails': string | null;
    'blobHref': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "startLine",
            "baseName": "start_line",
            "type": "number"
        },
        {
            "name": "endLine",
            "baseName": "end_line",
            "type": "number"
        },
        {
            "name": "startColumn",
            "baseName": "start_column",
            "type": "number"
        },
        {
            "name": "endColumn",
            "baseName": "end_column",
            "type": "number"
        },
        {
            "name": "annotationLevel",
            "baseName": "annotation_level",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "rawDetails",
            "baseName": "raw_details",
            "type": "string"
        },
        {
            "name": "blobHref",
            "baseName": "blob_href",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CheckAnnotation.attributeTypeMap;
    }
}

