/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CodespaceRuntimeConstraints {
    /**
    * The privacy settings a user can select from when forwarding a port.
    */
    'allowedPortPrivacySettings'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowedPortPrivacySettings",
            "baseName": "allowed_port_privacy_settings",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CodespaceRuntimeConstraints.attributeTypeMap;
    }
}

