/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CommitCommit } from './commitCommit';
import { CommitParentsInner } from './commitParentsInner';
import { CommitStats } from './commitStats';
import { DiffEntry } from './diffEntry';
import { SimpleUser } from './simpleUser';

/**
* Commit
*/
export class Commit {
    'url': string;
    'sha': string;
    'nodeId': string;
    'htmlUrl': string;
    'commentsUrl': string;
    'commit': CommitCommit;
    'author': SimpleUser | null;
    'committer': SimpleUser | null;
    'parents': Array<CommitParentsInner>;
    'stats'?: CommitStats;
    'files'?: Array<DiffEntry>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "sha",
            "baseName": "sha",
            "type": "string"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "htmlUrl",
            "baseName": "html_url",
            "type": "string"
        },
        {
            "name": "commentsUrl",
            "baseName": "comments_url",
            "type": "string"
        },
        {
            "name": "commit",
            "baseName": "commit",
            "type": "CommitCommit"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "SimpleUser"
        },
        {
            "name": "committer",
            "baseName": "committer",
            "type": "SimpleUser"
        },
        {
            "name": "parents",
            "baseName": "parents",
            "type": "Array<CommitParentsInner>"
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "CommitStats"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<DiffEntry>"
        }    ];

    static getAttributeTypeMap() {
        return Commit.attributeTypeMap;
    }
}

