/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReactionRollup } from './reactionRollup';
import { SimpleUser } from './simpleUser';

/**
* Commit Comment
*/
export class CommitComment {
    'htmlUrl': string;
    'url': string;
    'id': number;
    'nodeId': string;
    'body': string;
    'path': string | null;
    'position': number | null;
    'line': number | null;
    'commitId': string;
    'user': SimpleUser | null;
    'createdAt': Date;
    'updatedAt': Date;
    /**
    * How the author is associated with the repository.
    */
    'authorAssociation': CommitComment.AuthorAssociationEnum;
    'reactions'?: ReactionRollup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "htmlUrl",
            "baseName": "html_url",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "line",
            "baseName": "line",
            "type": "number"
        },
        {
            "name": "commitId",
            "baseName": "commit_id",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "SimpleUser"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "authorAssociation",
            "baseName": "author_association",
            "type": "CommitComment.AuthorAssociationEnum"
        },
        {
            "name": "reactions",
            "baseName": "reactions",
            "type": "ReactionRollup"
        }    ];

    static getAttributeTypeMap() {
        return CommitComment.attributeTypeMap;
    }
}

export namespace CommitComment {
    export enum AuthorAssociationEnum {
        Collaborator = <any> 'COLLABORATOR',
        Contributor = <any> 'CONTRIBUTOR',
        FirstTimer = <any> 'FIRST_TIMER',
        FirstTimeContributor = <any> 'FIRST_TIME_CONTRIBUTOR',
        Mannequin = <any> 'MANNEQUIN',
        Member = <any> 'MEMBER',
        None = <any> 'NONE',
        Owner = <any> 'OWNER'
    }
}
