/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrganizationSimple } from './organizationSimple';

export class EnterpriseAdminListSelectedOrganizationsEnabledGithubActionsEnterprise200Response {
    'totalCount': number;
    'organizations': Array<OrganizationSimple>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<OrganizationSimple>"
        }    ];

    static getAttributeTypeMap() {
        return EnterpriseAdminListSelectedOrganizationsEnabledGithubActionsEnterprise200Response.attributeTypeMap;
    }
}

