/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PendingDeploymentReviewersInner } from './pendingDeploymentReviewersInner';

export class EnvironmentProtectionRulesInnerAnyOf1 {
    'id': number;
    'nodeId': string;
    'type': string;
    /**
    * The people or teams that may approve jobs that reference the environment. You can list up to six users or teams as reviewers. The reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed.
    */
    'reviewers'?: Array<PendingDeploymentReviewersInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "reviewers",
            "baseName": "reviewers",
            "type": "Array<PendingDeploymentReviewersInner>"
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentProtectionRulesInnerAnyOf1.attributeTypeMap;
    }
}

