/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GistHistoryChangeStatus } from './gistHistoryChangeStatus';
import { SimpleUser } from './simpleUser';

/**
* Gist History
*/
export class GistHistory {
    'user'?: SimpleUser | null;
    'version'?: string;
    'committedAt'?: Date;
    'changeStatus'?: GistHistoryChangeStatus;
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "SimpleUser"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "committedAt",
            "baseName": "committed_at",
            "type": "Date"
        },
        {
            "name": "changeStatus",
            "baseName": "change_status",
            "type": "GistHistoryChangeStatus"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GistHistory.attributeTypeMap;
    }
}

