/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Interaction limit settings.
*/
export class InteractionLimits {
    /**
    * The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect.
    */
    'limit': InteractionLimits.LimitEnum;
    'origin': string;
    'expiresAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "InteractionLimits.LimitEnum"
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return InteractionLimits.attributeTypeMap;
    }
}

export namespace InteractionLimits {
    export enum LimitEnum {
        ExistingUsers = <any> 'existing_users',
        ContributorsOnly = <any> 'contributors_only',
        CollaboratorsOnly = <any> 'collaborators_only'
    }
}
