/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Issue Event Project Card
*/
export class IssueEventProjectCard {
    'url': string;
    'id': number;
    'projectUrl': string;
    'projectId': number;
    'columnName': string;
    'previousColumnName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "projectUrl",
            "baseName": "project_url",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "number"
        },
        {
            "name": "columnName",
            "baseName": "column_name",
            "type": "string"
        },
        {
            "name": "previousColumnName",
            "baseName": "previous_column_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IssueEventProjectCard.attributeTypeMap;
    }
}

