/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SearchResultTextMatchesInner } from './searchResultTextMatchesInner';

/**
* Label Search Result Item
*/
export class LabelSearchResultItem {
    'id': number;
    'nodeId': string;
    'url': string;
    'name': string;
    'color': string;
    '_default': boolean;
    'description': string | null;
    'score': number;
    'textMatches'?: Array<SearchResultTextMatchesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        },
        {
            "name": "textMatches",
            "baseName": "text_matches",
            "type": "Array<SearchResultTextMatchesInner>"
        }    ];

    static getAttributeTypeMap() {
        return LabelSearchResultItem.attributeTypeMap;
    }
}

