/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrganizationFullPlan } from './organizationFullPlan';

/**
* Organization Full
*/
export class OrganizationFull {
    'login': string;
    'id': number;
    'nodeId': string;
    'url': string;
    'reposUrl': string;
    'eventsUrl': string;
    'hooksUrl': string;
    'issuesUrl': string;
    'membersUrl': string;
    'publicMembersUrl': string;
    'avatarUrl': string;
    'description': string | null;
    'name'?: string;
    'company'?: string;
    'blog'?: string;
    'location'?: string;
    'email'?: string;
    'twitterUsername'?: string | null;
    'isVerified'?: boolean;
    'hasOrganizationProjects': boolean;
    'hasRepositoryProjects': boolean;
    'publicRepos': number;
    'publicGists': number;
    'followers': number;
    'following': number;
    'htmlUrl': string;
    'createdAt': Date;
    'type': string;
    'totalPrivateRepos'?: number;
    'ownedPrivateRepos'?: number;
    'privateGists'?: number | null;
    'diskUsage'?: number | null;
    'collaborators'?: number | null;
    'billingEmail'?: string | null;
    'plan'?: OrganizationFullPlan;
    'defaultRepositoryPermission'?: string | null;
    'membersCanCreateRepositories'?: boolean | null;
    'twoFactorRequirementEnabled'?: boolean | null;
    'membersAllowedRepositoryCreationType'?: string;
    'membersCanCreatePublicRepositories'?: boolean;
    'membersCanCreatePrivateRepositories'?: boolean;
    'membersCanCreateInternalRepositories'?: boolean;
    'membersCanCreatePages'?: boolean;
    'membersCanCreatePublicPages'?: boolean;
    'membersCanCreatePrivatePages'?: boolean;
    'membersCanForkPrivateRepositories'?: boolean | null;
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "reposUrl",
            "baseName": "repos_url",
            "type": "string"
        },
        {
            "name": "eventsUrl",
            "baseName": "events_url",
            "type": "string"
        },
        {
            "name": "hooksUrl",
            "baseName": "hooks_url",
            "type": "string"
        },
        {
            "name": "issuesUrl",
            "baseName": "issues_url",
            "type": "string"
        },
        {
            "name": "membersUrl",
            "baseName": "members_url",
            "type": "string"
        },
        {
            "name": "publicMembersUrl",
            "baseName": "public_members_url",
            "type": "string"
        },
        {
            "name": "avatarUrl",
            "baseName": "avatar_url",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string"
        },
        {
            "name": "blog",
            "baseName": "blog",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "twitterUsername",
            "baseName": "twitter_username",
            "type": "string"
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean"
        },
        {
            "name": "hasOrganizationProjects",
            "baseName": "has_organization_projects",
            "type": "boolean"
        },
        {
            "name": "hasRepositoryProjects",
            "baseName": "has_repository_projects",
            "type": "boolean"
        },
        {
            "name": "publicRepos",
            "baseName": "public_repos",
            "type": "number"
        },
        {
            "name": "publicGists",
            "baseName": "public_gists",
            "type": "number"
        },
        {
            "name": "followers",
            "baseName": "followers",
            "type": "number"
        },
        {
            "name": "following",
            "baseName": "following",
            "type": "number"
        },
        {
            "name": "htmlUrl",
            "baseName": "html_url",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "totalPrivateRepos",
            "baseName": "total_private_repos",
            "type": "number"
        },
        {
            "name": "ownedPrivateRepos",
            "baseName": "owned_private_repos",
            "type": "number"
        },
        {
            "name": "privateGists",
            "baseName": "private_gists",
            "type": "number"
        },
        {
            "name": "diskUsage",
            "baseName": "disk_usage",
            "type": "number"
        },
        {
            "name": "collaborators",
            "baseName": "collaborators",
            "type": "number"
        },
        {
            "name": "billingEmail",
            "baseName": "billing_email",
            "type": "string"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "OrganizationFullPlan"
        },
        {
            "name": "defaultRepositoryPermission",
            "baseName": "default_repository_permission",
            "type": "string"
        },
        {
            "name": "membersCanCreateRepositories",
            "baseName": "members_can_create_repositories",
            "type": "boolean"
        },
        {
            "name": "twoFactorRequirementEnabled",
            "baseName": "two_factor_requirement_enabled",
            "type": "boolean"
        },
        {
            "name": "membersAllowedRepositoryCreationType",
            "baseName": "members_allowed_repository_creation_type",
            "type": "string"
        },
        {
            "name": "membersCanCreatePublicRepositories",
            "baseName": "members_can_create_public_repositories",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePrivateRepositories",
            "baseName": "members_can_create_private_repositories",
            "type": "boolean"
        },
        {
            "name": "membersCanCreateInternalRepositories",
            "baseName": "members_can_create_internal_repositories",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePages",
            "baseName": "members_can_create_pages",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePublicPages",
            "baseName": "members_can_create_public_pages",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePrivatePages",
            "baseName": "members_can_create_private_pages",
            "type": "boolean"
        },
        {
            "name": "membersCanForkPrivateRepositories",
            "baseName": "members_can_fork_private_repositories",
            "type": "boolean"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationFull.attributeTypeMap;
    }
}

