/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrgHookConfig } from './orgHookConfig';

/**
* Org Hook
*/
export class OrgHook {
    'id': number;
    'url': string;
    'pingUrl': string;
    'deliveriesUrl'?: string;
    'name': string;
    'events': Array<string>;
    'active': boolean;
    'config': OrgHookConfig;
    'updatedAt': Date;
    'createdAt': Date;
    'type': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "pingUrl",
            "baseName": "ping_url",
            "type": "string"
        },
        {
            "name": "deliveriesUrl",
            "baseName": "deliveries_url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<string>"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "OrgHookConfig"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrgHook.attributeTypeMap;
    }
}

