/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrgsUpdateRequest {
    /**
    * Billing email address. This address is not publicized.
    */
    'billingEmail'?: string;
    /**
    * The company name.
    */
    'company'?: string;
    /**
    * The publicly visible email address.
    */
    'email'?: string;
    /**
    * The Twitter username of the company.
    */
    'twitterUsername'?: string;
    /**
    * The location.
    */
    'location'?: string;
    /**
    * The shorthand name of the company.
    */
    'name'?: string;
    /**
    * The description of the company.
    */
    'description'?: string;
    /**
    * Whether an organization can use organization projects.
    */
    'hasOrganizationProjects'?: boolean;
    /**
    * Whether repositories that belong to the organization can use repository projects.
    */
    'hasRepositoryProjects'?: boolean;
    /**
    * Default permission level members have for organization repositories.
    */
    'defaultRepositoryPermission'?: OrgsUpdateRequest.DefaultRepositoryPermissionEnum = OrgsUpdateRequest.DefaultRepositoryPermissionEnum.Read;
    /**
    * Whether of non-admin organization members can create repositories. **Note:** A parameter can override this parameter. See `members_allowed_repository_creation_type` in this table for details.
    */
    'membersCanCreateRepositories'?: boolean = true;
    /**
    * Whether organization members can create internal repositories, which are visible to all enterprise members. You can only allow members to create internal repositories if your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+. For more information, see \"[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\" in the GitHub Help documentation.
    */
    'membersCanCreateInternalRepositories'?: boolean;
    /**
    * Whether organization members can create private repositories, which are visible to organization members with permission. For more information, see \"[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\" in the GitHub Help documentation.
    */
    'membersCanCreatePrivateRepositories'?: boolean;
    /**
    * Whether organization members can create public repositories, which are visible to anyone. For more information, see \"[Restricting repository creation in your organization](https://docs.github.com/github/setting-up-and-managing-organizations-and-teams/restricting-repository-creation-in-your-organization)\" in the GitHub Help documentation.
    */
    'membersCanCreatePublicRepositories'?: boolean;
    /**
    * Specifies which types of repositories non-admin organization members can create. `private` is only available to repositories that are part of an organization on GitHub Enterprise Cloud.  **Note:** This parameter is deprecated and will be removed in the future. Its return value ignores internal repositories. Using this parameter overrides values set in `members_can_create_repositories`. See the parameter deprecation notice in the operation description for details.
    */
    'membersAllowedRepositoryCreationType'?: OrgsUpdateRequest.MembersAllowedRepositoryCreationTypeEnum;
    /**
    * Whether organization members can create GitHub Pages sites. Existing published sites will not be impacted.
    */
    'membersCanCreatePages'?: boolean = true;
    /**
    * Whether organization members can create public GitHub Pages sites. Existing published sites will not be impacted.
    */
    'membersCanCreatePublicPages'?: boolean = true;
    /**
    * Whether organization members can create private GitHub Pages sites. Existing published sites will not be impacted.
    */
    'membersCanCreatePrivatePages'?: boolean = true;
    /**
    * Whether organization members can fork private organization repositories.
    */
    'membersCanForkPrivateRepositories'?: boolean = false;
    'blog'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billingEmail",
            "baseName": "billing_email",
            "type": "string"
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "twitterUsername",
            "baseName": "twitter_username",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "hasOrganizationProjects",
            "baseName": "has_organization_projects",
            "type": "boolean"
        },
        {
            "name": "hasRepositoryProjects",
            "baseName": "has_repository_projects",
            "type": "boolean"
        },
        {
            "name": "defaultRepositoryPermission",
            "baseName": "default_repository_permission",
            "type": "OrgsUpdateRequest.DefaultRepositoryPermissionEnum"
        },
        {
            "name": "membersCanCreateRepositories",
            "baseName": "members_can_create_repositories",
            "type": "boolean"
        },
        {
            "name": "membersCanCreateInternalRepositories",
            "baseName": "members_can_create_internal_repositories",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePrivateRepositories",
            "baseName": "members_can_create_private_repositories",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePublicRepositories",
            "baseName": "members_can_create_public_repositories",
            "type": "boolean"
        },
        {
            "name": "membersAllowedRepositoryCreationType",
            "baseName": "members_allowed_repository_creation_type",
            "type": "OrgsUpdateRequest.MembersAllowedRepositoryCreationTypeEnum"
        },
        {
            "name": "membersCanCreatePages",
            "baseName": "members_can_create_pages",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePublicPages",
            "baseName": "members_can_create_public_pages",
            "type": "boolean"
        },
        {
            "name": "membersCanCreatePrivatePages",
            "baseName": "members_can_create_private_pages",
            "type": "boolean"
        },
        {
            "name": "membersCanForkPrivateRepositories",
            "baseName": "members_can_fork_private_repositories",
            "type": "boolean"
        },
        {
            "name": "blog",
            "baseName": "blog",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrgsUpdateRequest.attributeTypeMap;
    }
}

export namespace OrgsUpdateRequest {
    export enum DefaultRepositoryPermissionEnum {
        Read = <any> 'read',
        Write = <any> 'write',
        Admin = <any> 'admin',
        None = <any> 'none'
    }
    export enum MembersAllowedRepositoryCreationTypeEnum {
        All = <any> 'all',
        Private = <any> 'private',
        None = <any> 'none'
    }
}
