/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProjectsAddCollaboratorRequest {
    /**
    * The permission to grant the collaborator.
    */
    'permission'?: ProjectsAddCollaboratorRequest.PermissionEnum = ProjectsAddCollaboratorRequest.PermissionEnum.Write;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permission",
            "baseName": "permission",
            "type": "ProjectsAddCollaboratorRequest.PermissionEnum"
        }    ];

    static getAttributeTypeMap() {
        return ProjectsAddCollaboratorRequest.attributeTypeMap;
    }
}

export namespace ProjectsAddCollaboratorRequest {
    export enum PermissionEnum {
        Read = <any> 'read',
        Write = <any> 'write',
        Admin = <any> 'admin'
    }
}
