/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GitHubApp } from './gitHubApp';
import { SimpleUser1 } from './simpleUser1';
import { Team } from './team';

export class ProtectedBranchPullRequestReviewDismissalRestrictions {
    /**
    * The list of users with review dismissal access.
    */
    'users'?: Array<SimpleUser1>;
    /**
    * The list of teams with review dismissal access.
    */
    'teams'?: Array<Team>;
    /**
    * The list of apps with review dismissal access.
    */
    'apps'?: Array<GitHubApp>;
    'url'?: string;
    'usersUrl'?: string;
    'teamsUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<SimpleUser1>"
        },
        {
            "name": "teams",
            "baseName": "teams",
            "type": "Array<Team>"
        },
        {
            "name": "apps",
            "baseName": "apps",
            "type": "Array<GitHubApp>"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "usersUrl",
            "baseName": "users_url",
            "type": "string"
        },
        {
            "name": "teamsUrl",
            "baseName": "teams_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProtectedBranchPullRequestReviewDismissalRestrictions.attributeTypeMap;
    }
}

