/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GitHubApp } from './gitHubApp';
import { SimpleUser1 } from './simpleUser1';
import { Team } from './team';

export class ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowances {
    'users': Array<SimpleUser1>;
    'teams': Array<Team>;
    'apps'?: Array<GitHubApp>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<SimpleUser1>"
        },
        {
            "name": "teams",
            "baseName": "teams",
            "type": "Array<Team>"
        },
        {
            "name": "apps",
            "baseName": "apps",
            "type": "Array<GitHubApp>"
        }    ];

    static getAttributeTypeMap() {
        return ProtectedBranchRequiredPullRequestReviewsBypassPullRequestAllowances.attributeTypeMap;
    }
}

