/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Repository } from './repository';
import { SimpleUser } from './simpleUser';

export class PullRequestSimpleHead {
    'label': string;
    'ref': string;
    'repo': Repository;
    'sha': string;
    'user': SimpleUser | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "ref",
            "baseName": "ref",
            "type": "string"
        },
        {
            "name": "repo",
            "baseName": "repo",
            "type": "Repository"
        },
        {
            "name": "sha",
            "baseName": "sha",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "SimpleUser"
        }    ];

    static getAttributeTypeMap() {
        return PullRequestSimpleHead.attributeTypeMap;
    }
}

