/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReposUpdateInformationAboutPagesSiteRequestSource } from './reposUpdateInformationAboutPagesSiteRequestSource';

export class ReposUpdateInformationAboutPagesSiteRequest {
    /**
    * Specify a custom domain for the repository. Sending a `null` value will remove the custom domain. For more about custom domains, see \"[Using a custom domain with GitHub Pages](https://docs.github.com/articles/using-a-custom-domain-with-github-pages/).\"
    */
    'cname'?: string | null;
    /**
    * Specify whether HTTPS should be enforced for the repository.
    */
    'httpsEnforced'?: boolean;
    /**
    * Configures access controls for the GitHub Pages site. If public is set to `true`, the site is accessible to anyone on the internet. If set to `false`, the site will only be accessible to users who have at least `read` access to the repository that published the site. This includes anyone in your Enterprise if the repository is set to `internal` visibility. This feature is only available to repositories in an organization on an Enterprise plan.
    */
    '_public'?: boolean;
    /**
    * The process by which the GitHub Pages site will be built. `workflow` means that the site is built by a custom GitHub Actions workflow. `legacy` means that the site is built by GitHub when changes are pushed to a specific branch.
    */
    'buildType'?: ReposUpdateInformationAboutPagesSiteRequest.BuildTypeEnum;
    'source'?: ReposUpdateInformationAboutPagesSiteRequestSource;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cname",
            "baseName": "cname",
            "type": "string"
        },
        {
            "name": "httpsEnforced",
            "baseName": "https_enforced",
            "type": "boolean"
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean"
        },
        {
            "name": "buildType",
            "baseName": "build_type",
            "type": "ReposUpdateInformationAboutPagesSiteRequest.BuildTypeEnum"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ReposUpdateInformationAboutPagesSiteRequestSource"
        }    ];

    static getAttributeTypeMap() {
        return ReposUpdateInformationAboutPagesSiteRequest.attributeTypeMap;
    }
}

