/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { IssueSearchResultItem } from './issueSearchResultItem';

export class SearchIssuesAndPullRequests200Response {
    'totalCount': number;
    'incompleteResults': boolean;
    'items': Array<IssueSearchResultItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        },
        {
            "name": "incompleteResults",
            "baseName": "incomplete_results",
            "type": "boolean"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<IssueSearchResultItem>"
        }    ];

    static getAttributeTypeMap() {
        return SearchIssuesAndPullRequests200Response.attributeTypeMap;
    }
}

