/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents a \'commit\' secret scanning location type. This location type shows that a secret was detected inside a commit to a repository.
*/
export class SecretScanningListLocationsForAlert200ResponseInnerDetailsOneOf {
    /**
    * The file path in the repository
    */
    'path': string;
    /**
    * Line number at which the secret starts in the file
    */
    'startLine': number;
    /**
    * Line number at which the secret ends in the file
    */
    'endLine': number;
    /**
    * The column at which the secret starts within the start line when the file is interpreted as 8BIT ASCII
    */
    'startColumn': number;
    /**
    * The column at which the secret ends within the end line when the file is interpreted as 8BIT ASCII
    */
    'endColumn': number;
    /**
    * SHA-1 hash ID of the associated blob
    */
    'blobSha': string;
    /**
    * The API URL to get the associated blob resource
    */
    'blobUrl': string;
    /**
    * SHA-1 hash ID of the associated commit
    */
    'commitSha': string;
    /**
    * The API URL to get the associated commit resource
    */
    'commitUrl': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "startLine",
            "baseName": "start_line",
            "type": "number"
        },
        {
            "name": "endLine",
            "baseName": "end_line",
            "type": "number"
        },
        {
            "name": "startColumn",
            "baseName": "start_column",
            "type": "number"
        },
        {
            "name": "endColumn",
            "baseName": "end_column",
            "type": "number"
        },
        {
            "name": "blobSha",
            "baseName": "blob_sha",
            "type": "string"
        },
        {
            "name": "blobUrl",
            "baseName": "blob_url",
            "type": "string"
        },
        {
            "name": "commitSha",
            "baseName": "commit_sha",
            "type": "string"
        },
        {
            "name": "commitUrl",
            "baseName": "commit_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SecretScanningListLocationsForAlert200ResponseInnerDetailsOneOf.attributeTypeMap;
    }
}

