/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ServerStatisticsProxyEndpointInnerGheStatsMilestones {
    'totalMilestones'?: number;
    'openMilestones'?: number;
    'closedMilestones'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalMilestones",
            "baseName": "total_milestones",
            "type": "number"
        },
        {
            "name": "openMilestones",
            "baseName": "open_milestones",
            "type": "number"
        },
        {
            "name": "closedMilestones",
            "baseName": "closed_milestones",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ServerStatisticsProxyEndpointInnerGheStatsMilestones.attributeTypeMap;
    }
}

