/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SimpleUser1 } from './simpleUser1';
import { TeamProjectPermissions } from './teamProjectPermissions';

/**
* A team\'s access to a project.
*/
export class TeamProject {
    'ownerUrl': string;
    'url': string;
    'htmlUrl': string;
    'columnsUrl': string;
    'id': number;
    'nodeId': string;
    'name': string;
    'body': string | null;
    'number': number;
    'state': string;
    'creator': SimpleUser1;
    'createdAt': string;
    'updatedAt': string;
    /**
    * The organization permission for this project. Only present when owner is an organization.
    */
    'organizationPermission'?: string;
    /**
    * Whether the project is private or not. Only present when owner is an organization.
    */
    '_private'?: boolean;
    'permissions': TeamProjectPermissions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ownerUrl",
            "baseName": "owner_url",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "htmlUrl",
            "baseName": "html_url",
            "type": "string"
        },
        {
            "name": "columnsUrl",
            "baseName": "columns_url",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "nodeId",
            "baseName": "node_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "SimpleUser1"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "organizationPermission",
            "baseName": "organization_permission",
            "type": "string"
        },
        {
            "name": "_private",
            "baseName": "private",
            "type": "boolean"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "TeamProjectPermissions"
        }    ];

    static getAttributeTypeMap() {
        return TeamProject.attributeTypeMap;
    }
}

