/**
 * GitHub v3 REST API
 * GitHub\'s v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SimpleUser1 } from './simpleUser1';
import { TimelineCrossReferencedEventSource } from './timelineCrossReferencedEventSource';

/**
* Timeline Cross Referenced Event
*/
export class TimelineCrossReferencedEvent {
    'event': string;
    'actor'?: SimpleUser1;
    'createdAt': Date;
    'updatedAt': Date;
    'source': TimelineCrossReferencedEventSource;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "event",
            "baseName": "event",
            "type": "string"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "SimpleUser1"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "TimelineCrossReferencedEventSource"
        }    ];

    static getAttributeTypeMap() {
        return TimelineCrossReferencedEvent.attributeTypeMap;
    }
}

