=begin
#GitHub v3 REST API

#GitHub's v3 REST API.

The version of the OpenAPI document: 1.1.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MarkdownApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MarkdownApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MarkdownApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarkdownApi' do
    it 'should create an instance of MarkdownApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MarkdownApi)
    end
  end

  # unit tests for markdown_render
  # Render a Markdown document
  # 
  # @param markdown_render_request 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'markdown_render test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for markdown_render_raw
  # Render a Markdown document in raw mode
  # You must send Markdown as plain text (using a &#x60;Content-Type&#x60; header of &#x60;text/plain&#x60; or &#x60;text/x-markdown&#x60;) to this endpoint, rather than using JSON format. In raw mode, [GitHub Flavored Markdown](https://github.github.com/gfm/) is not supported and Markdown will be rendered in plain format like a README.md file. Markdown content must be 400 KB or less.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :body 
  # @return [String]
  describe 'markdown_render_raw test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
